<?php

namespace FrontOfficeBundle\Repository;

/**
 * ChampionnatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampionnatRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAll(){
        $queryBuilder=$this->createQueryBuilder('champ');
        $query=$queryBuilder->getQuery();
        $results=$query->getResult();
        return $results;
    }

    public function getChampionnatIDBIS($nomChampionnat){
        $queryBuilder = $this->createQueryBuilder('c');
        $queryBuilder->where('c.nom!=:nomChampionnat')
            ->setParameter('nomChampionnat',$nomChampionnat);
        $query = $queryBuilder->getQuery();

        return $query->getResult();
    }
}
