<?php

namespace FrontOfficeBundle\Repository;

/**
 * DiffuseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiffuseurRepository extends \Doctrine\ORM\EntityRepository
{
}
