<?php

namespace FrontOfficeBundle\Repository;

/**
 * EquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipeRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAllEquipesDuTop14(){
        //création du queryBuilder paramétré avec l'alias de l'entité événement
        $queryBuilder=$this->createQueryBuilder('equipe');
        //récupération de la query à partir du queryBuilder
        $query=$queryBuilder->getQuery();
        //récupération du résultat à partir de la query
        $results=$query->getResult();
        //on retourne les résultats
        return $results;
    }
}
