<?php

namespace FrontOfficeBundle\Repository;

/**
 * JoueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getJoueurEquipe($equipe){
        $queryBuilder = $this->createQueryBuilder('j');
         $queryBuilder->innerJoin('FrontOfficeBundle:Equipe','e')
                     ->andWhere("e.id = :equipe")
                     //->andWhere("e.id = j.equipe")
            ->setParameter('equipe',$equipe);

        $query=$queryBuilder->getQuery();

        return $query->getResult();
    }
}
