<?php

namespace FrontOfficeBundle\Repository;

/**
 * JourneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourneeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getJourneeChampionnat($championnat){
        $queryBuilder = $this->createQueryBuilder('j');
        $queryBuilder->innerJoin('FrontOfficeBundle:Championnat','c','with','j.championnat = c.id')
            ->where('c.nom = :championnat order by j.nom DESC')
            ->setParameter('championnat',$championnat);
        $query=$queryBuilder->getQuery();

        return $query->getResult();
    }
}
