back_office:
    resource: "@BackOfficeBundle/Controller/"
    type:     annotation
    prefix:   /

front_office:
    resource: "@FrontOfficeBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
