back_office:
    resource: "@BackOfficeBundle/Controller/"
    type:     annotation
    prefix:   /admin/

front_office:
    resource: "@FrontOfficeBundle/Controller/"
    type:     annotation
    prefix:   /